stages:
- name: java
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: 'cd 6_docker-build && mvn clean '
- name: docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: springbootvd
      pushRemote: true
      registry: registry.cn-hangzhou.aliyuncs.com
- name: publish
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
